// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: whitelist/voter.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Voter struct {
	VoterId     string   `protobuf:"bytes,1,opt,name=voterId,proto3" json:"voterId,omitempty"`
	Name        string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	VotingPower uint64   `protobuf:"varint,3,opt,name=votingPower,proto3" json:"votingPower,omitempty"`
	NumVotes    uint64   `protobuf:"varint,4,opt,name=numVotes,proto3" json:"numVotes,omitempty"`
	VoteId      []string `protobuf:"bytes,5,rep,name=voteId,proto3" json:"voteId,omitempty"`
	Status      string   `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Reviewer    string   `protobuf:"bytes,7,opt,name=reviewer,proto3" json:"reviewer,omitempty"`
}

func (m *Voter) Reset()         { *m = Voter{} }
func (m *Voter) String() string { return proto.CompactTextString(m) }
func (*Voter) ProtoMessage()    {}
func (*Voter) Descriptor() ([]byte, []int) {
	return fileDescriptor_26a5acf3bf12ef6f, []int{0}
}
func (m *Voter) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Voter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Voter.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Voter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Voter.Merge(m, src)
}
func (m *Voter) XXX_Size() int {
	return m.Size()
}
func (m *Voter) XXX_DiscardUnknown() {
	xxx_messageInfo_Voter.DiscardUnknown(m)
}

var xxx_messageInfo_Voter proto.InternalMessageInfo

func (m *Voter) GetVoterId() string {
	if m != nil {
		return m.VoterId
	}
	return ""
}

func (m *Voter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Voter) GetVotingPower() uint64 {
	if m != nil {
		return m.VotingPower
	}
	return 0
}

func (m *Voter) GetNumVotes() uint64 {
	if m != nil {
		return m.NumVotes
	}
	return 0
}

func (m *Voter) GetVoteId() []string {
	if m != nil {
		return m.VoteId
	}
	return nil
}

func (m *Voter) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Voter) GetReviewer() string {
	if m != nil {
		return m.Reviewer
	}
	return ""
}

func init() {
	proto.RegisterType((*Voter)(nil), "crowlabs.delta.whitelist.Voter")
}

func init() { proto.RegisterFile("whitelist/voter.proto", fileDescriptor_26a5acf3bf12ef6f) }

var fileDescriptor_26a5acf3bf12ef6f = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x63, 0x9a, 0xa6, 0xd4, 0x6c, 0x96, 0x40, 0x16, 0x83, 0x15, 0x31, 0x65, 0x80, 0x78,
	0xe0, 0x0d, 0x18, 0x90, 0xba, 0xa1, 0x0c, 0x0c, 0x6c, 0x4e, 0x63, 0xb5, 0x96, 0x92, 0xb8, 0xb2,
	0x2f, 0x09, 0xbc, 0x05, 0x6f, 0xc4, 0xca, 0xd8, 0x91, 0x11, 0x25, 0x2f, 0x82, 0x7c, 0x2a, 0x81,
	0xcd, 0xdf, 0x7f, 0xe7, 0xff, 0xa4, 0x8f, 0x5e, 0x0e, 0x7b, 0x03, 0xba, 0x36, 0x1e, 0x64, 0x6f,
	0x41, 0xbb, 0xfc, 0xe0, 0x2c, 0x58, 0xc6, 0xb7, 0xce, 0x0e, 0xb5, 0x2a, 0x7d, 0x5e, 0xe9, 0x1a,
	0x54, 0x3e, 0x6f, 0xdd, 0x7c, 0x10, 0xba, 0x7c, 0x0e, 0x9b, 0x8c, 0xd3, 0x15, 0x7e, 0xd9, 0x54,
	0x9c, 0xa4, 0x24, 0x5b, 0x17, 0xbf, 0xc8, 0x18, 0x8d, 0x5b, 0xd5, 0x68, 0x7e, 0x86, 0x31, 0xbe,
	0x59, 0x4a, 0x2f, 0x7a, 0x0b, 0xa6, 0xdd, 0x3d, 0xd9, 0x41, 0x3b, 0xbe, 0x48, 0x49, 0x16, 0x17,
	0xff, 0x23, 0x76, 0x4d, 0xcf, 0xdb, 0xae, 0x09, 0xdd, 0x9e, 0xc7, 0x38, 0x9e, 0x99, 0x5d, 0xd1,
	0x24, 0x94, 0x6f, 0x2a, 0xbe, 0x4c, 0x17, 0xd9, 0xba, 0x38, 0x51, 0xc8, 0x3d, 0x28, 0xe8, 0x3c,
	0x4f, 0xf0, 0xd6, 0x89, 0x42, 0x97, 0xd3, 0xbd, 0xd1, 0xe1, 0xd4, 0x0a, 0x27, 0x33, 0x3f, 0x3c,
	0x7e, 0x8e, 0x82, 0x1c, 0x47, 0x41, 0xbe, 0x47, 0x41, 0xde, 0x27, 0x11, 0x1d, 0x27, 0x11, 0x7d,
	0x4d, 0x22, 0x7a, 0xb9, 0xdd, 0x19, 0xd8, 0x77, 0x65, 0xbe, 0xb5, 0x8d, 0x0c, 0x02, 0xee, 0x82,
	0x01, 0x89, 0x06, 0xe4, 0xab, 0xfc, 0x33, 0x05, 0x6f, 0x07, 0xed, 0xcb, 0x04, 0x55, 0xdd, 0xff,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x00, 0xe4, 0x0d, 0x6b, 0x43, 0x01, 0x00, 0x00,
}

func (m *Voter) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Voter) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Voter) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reviewer) > 0 {
		i -= len(m.Reviewer)
		copy(dAtA[i:], m.Reviewer)
		i = encodeVarintVoter(dAtA, i, uint64(len(m.Reviewer)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintVoter(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.VoteId) > 0 {
		for iNdEx := len(m.VoteId) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.VoteId[iNdEx])
			copy(dAtA[i:], m.VoteId[iNdEx])
			i = encodeVarintVoter(dAtA, i, uint64(len(m.VoteId[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.NumVotes != 0 {
		i = encodeVarintVoter(dAtA, i, uint64(m.NumVotes))
		i--
		dAtA[i] = 0x20
	}
	if m.VotingPower != 0 {
		i = encodeVarintVoter(dAtA, i, uint64(m.VotingPower))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintVoter(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.VoterId) > 0 {
		i -= len(m.VoterId)
		copy(dAtA[i:], m.VoterId)
		i = encodeVarintVoter(dAtA, i, uint64(len(m.VoterId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintVoter(dAtA []byte, offset int, v uint64) int {
	offset -= sovVoter(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Voter) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.VoterId)
	if l > 0 {
		n += 1 + l + sovVoter(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovVoter(uint64(l))
	}
	if m.VotingPower != 0 {
		n += 1 + sovVoter(uint64(m.VotingPower))
	}
	if m.NumVotes != 0 {
		n += 1 + sovVoter(uint64(m.NumVotes))
	}
	if len(m.VoteId) > 0 {
		for _, s := range m.VoteId {
			l = len(s)
			n += 1 + l + sovVoter(uint64(l))
		}
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovVoter(uint64(l))
	}
	l = len(m.Reviewer)
	if l > 0 {
		n += 1 + l + sovVoter(uint64(l))
	}
	return n
}

func sovVoter(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVoter(x uint64) (n int) {
	return sovVoter(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Voter) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVoter
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Voter: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Voter: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoterId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoter
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVoter
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVoter
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VoterId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoter
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVoter
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVoter
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotingPower", wireType)
			}
			m.VotingPower = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoter
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VotingPower |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumVotes", wireType)
			}
			m.NumVotes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoter
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumVotes |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoter
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVoter
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVoter
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VoteId = append(m.VoteId, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoter
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVoter
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVoter
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reviewer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoter
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVoter
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVoter
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reviewer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVoter(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVoter
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVoter(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVoter
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVoter
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVoter
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVoter
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVoter
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVoter
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVoter        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVoter          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVoter = fmt.Errorf("proto: unexpected end of group")
)
