// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: escrow/rebuttal.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Rebuttal struct {
	DisputeId   string `protobuf:"bytes,1,opt,name=disputeId,proto3" json:"disputeId,omitempty"`
	DefendantId string `protobuf:"bytes,2,opt,name=defendantId,proto3" json:"defendantId,omitempty"`
	RebuttalId  string `protobuf:"bytes,3,opt,name=rebuttalId,proto3" json:"rebuttalId,omitempty"`
}

func (m *Rebuttal) Reset()         { *m = Rebuttal{} }
func (m *Rebuttal) String() string { return proto.CompactTextString(m) }
func (*Rebuttal) ProtoMessage()    {}
func (*Rebuttal) Descriptor() ([]byte, []int) {
	return fileDescriptor_c97fab2f50618abe, []int{0}
}
func (m *Rebuttal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Rebuttal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Rebuttal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Rebuttal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rebuttal.Merge(m, src)
}
func (m *Rebuttal) XXX_Size() int {
	return m.Size()
}
func (m *Rebuttal) XXX_DiscardUnknown() {
	xxx_messageInfo_Rebuttal.DiscardUnknown(m)
}

var xxx_messageInfo_Rebuttal proto.InternalMessageInfo

func (m *Rebuttal) GetDisputeId() string {
	if m != nil {
		return m.DisputeId
	}
	return ""
}

func (m *Rebuttal) GetDefendantId() string {
	if m != nil {
		return m.DefendantId
	}
	return ""
}

func (m *Rebuttal) GetRebuttalId() string {
	if m != nil {
		return m.RebuttalId
	}
	return ""
}

func init() {
	proto.RegisterType((*Rebuttal)(nil), "crowlabs.delta.escrow.Rebuttal")
}

func init() { proto.RegisterFile("escrow/rebuttal.proto", fileDescriptor_c97fab2f50618abe) }

var fileDescriptor_c97fab2f50618abe = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0x2d, 0x4e, 0x2e,
	0xca, 0x2f, 0xd7, 0x2f, 0x4a, 0x4d, 0x2a, 0x2d, 0x29, 0x49, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x12, 0x05, 0x09, 0xe6, 0x24, 0x26, 0x15, 0xeb, 0xa5, 0xa4, 0xe6, 0x94, 0x24, 0xea,
	0x41, 0x54, 0x29, 0x65, 0x71, 0x71, 0x04, 0x41, 0x15, 0x0a, 0xc9, 0x70, 0x71, 0xa6, 0x64, 0x16,
	0x17, 0x94, 0x96, 0xa4, 0x7a, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x21, 0x04, 0x84,
	0x14, 0xb8, 0xb8, 0x53, 0x52, 0xd3, 0x52, 0xf3, 0x52, 0x12, 0xf3, 0x4a, 0x3c, 0x53, 0x24, 0x98,
	0xc0, 0xf2, 0xc8, 0x42, 0x42, 0x72, 0x5c, 0x5c, 0x30, 0x4b, 0x3d, 0x53, 0x24, 0x98, 0xc1, 0x0a,
	0x90, 0x44, 0x9c, 0x9c, 0x4f, 0x3c, 0x92, 0x63, 0xbc, 0xf0, 0x48, 0x8e, 0xf1, 0xc1, 0x23, 0x39,
	0xc6, 0x09, 0x8f, 0xe5, 0x18, 0x2e, 0x3c, 0x96, 0x63, 0xb8, 0xf1, 0x58, 0x8e, 0x21, 0x4a, 0x33,
	0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0x1f, 0xe4, 0x2c, 0x5d, 0x90, 0x43,
	0xf5, 0xc1, 0x0e, 0xd5, 0xaf, 0xd0, 0x87, 0x7a, 0xa8, 0xa4, 0xb2, 0x20, 0xb5, 0x38, 0x89, 0x0d,
	0xec, 0x1d, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbb, 0x48, 0x23, 0xc4, 0xe7, 0x00, 0x00,
	0x00,
}

func (m *Rebuttal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Rebuttal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Rebuttal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RebuttalId) > 0 {
		i -= len(m.RebuttalId)
		copy(dAtA[i:], m.RebuttalId)
		i = encodeVarintRebuttal(dAtA, i, uint64(len(m.RebuttalId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DefendantId) > 0 {
		i -= len(m.DefendantId)
		copy(dAtA[i:], m.DefendantId)
		i = encodeVarintRebuttal(dAtA, i, uint64(len(m.DefendantId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.DisputeId) > 0 {
		i -= len(m.DisputeId)
		copy(dAtA[i:], m.DisputeId)
		i = encodeVarintRebuttal(dAtA, i, uint64(len(m.DisputeId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintRebuttal(dAtA []byte, offset int, v uint64) int {
	offset -= sovRebuttal(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Rebuttal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DisputeId)
	if l > 0 {
		n += 1 + l + sovRebuttal(uint64(l))
	}
	l = len(m.DefendantId)
	if l > 0 {
		n += 1 + l + sovRebuttal(uint64(l))
	}
	l = len(m.RebuttalId)
	if l > 0 {
		n += 1 + l + sovRebuttal(uint64(l))
	}
	return n
}

func sovRebuttal(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRebuttal(x uint64) (n int) {
	return sovRebuttal(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Rebuttal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRebuttal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Rebuttal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Rebuttal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisputeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRebuttal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRebuttal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRebuttal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DisputeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefendantId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRebuttal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRebuttal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRebuttal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DefendantId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RebuttalId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRebuttal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRebuttal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRebuttal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RebuttalId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRebuttal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRebuttal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRebuttal(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRebuttal
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRebuttal
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRebuttal
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRebuttal
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRebuttal
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRebuttal
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRebuttal        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRebuttal          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRebuttal = fmt.Errorf("proto: unexpected end of group")
)
