// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: escrow/vote.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Vote struct {
	VoteId           string       `protobuf:"bytes,1,opt,name=voteId,proto3" json:"voteId,omitempty"`
	BuyerGuilty      bool         `protobuf:"varint,2,opt,name=buyerGuilty,proto3" json:"buyerGuilty,omitempty"`
	SellerGuilty     bool         `protobuf:"varint,3,opt,name=sellerGuilty,proto3" json:"sellerGuilty,omitempty"`
	RefundToBuyer    []types.Coin `protobuf:"bytes,4,rep,name=refundToBuyer,proto3" json:"refundToBuyer"`
	SendToSeller     []types.Coin `protobuf:"bytes,5,rep,name=sendToSeller,proto3" json:"sendToSeller"`
	BuyerPunishment  string       `protobuf:"bytes,6,opt,name=buyerPunishment,proto3" json:"buyerPunishment,omitempty"`
	SellerPunishment string       `protobuf:"bytes,7,opt,name=sellerPunishment,proto3" json:"sellerPunishment,omitempty"`
	Voter            string       `protobuf:"bytes,8,opt,name=voter,proto3" json:"voter,omitempty"`
}

func (m *Vote) Reset()         { *m = Vote{} }
func (m *Vote) String() string { return proto.CompactTextString(m) }
func (*Vote) ProtoMessage()    {}
func (*Vote) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa4b5642e19b921b, []int{0}
}
func (m *Vote) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Vote.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Vote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vote.Merge(m, src)
}
func (m *Vote) XXX_Size() int {
	return m.Size()
}
func (m *Vote) XXX_DiscardUnknown() {
	xxx_messageInfo_Vote.DiscardUnknown(m)
}

var xxx_messageInfo_Vote proto.InternalMessageInfo

func (m *Vote) GetVoteId() string {
	if m != nil {
		return m.VoteId
	}
	return ""
}

func (m *Vote) GetBuyerGuilty() bool {
	if m != nil {
		return m.BuyerGuilty
	}
	return false
}

func (m *Vote) GetSellerGuilty() bool {
	if m != nil {
		return m.SellerGuilty
	}
	return false
}

func (m *Vote) GetRefundToBuyer() []types.Coin {
	if m != nil {
		return m.RefundToBuyer
	}
	return nil
}

func (m *Vote) GetSendToSeller() []types.Coin {
	if m != nil {
		return m.SendToSeller
	}
	return nil
}

func (m *Vote) GetBuyerPunishment() string {
	if m != nil {
		return m.BuyerPunishment
	}
	return ""
}

func (m *Vote) GetSellerPunishment() string {
	if m != nil {
		return m.SellerPunishment
	}
	return ""
}

func (m *Vote) GetVoter() string {
	if m != nil {
		return m.Voter
	}
	return ""
}

func init() {
	proto.RegisterType((*Vote)(nil), "crowlabs.delta.escrow.Vote")
}

func init() { proto.RegisterFile("escrow/vote.proto", fileDescriptor_fa4b5642e19b921b) }

var fileDescriptor_fa4b5642e19b921b = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcf, 0x4e, 0x32, 0x31,
	0x14, 0xc5, 0x67, 0xf8, 0xf7, 0xf1, 0x15, 0x8d, 0xda, 0xa0, 0xa9, 0x2c, 0xea, 0x84, 0xd5, 0x68,
	0x62, 0x1b, 0xf4, 0x0d, 0x20, 0xc6, 0xb8, 0x33, 0x68, 0x5c, 0xb8, 0x9b, 0x0e, 0x15, 0x26, 0x19,
	0xe6, 0x92, 0x69, 0x07, 0xe5, 0x2d, 0x7c, 0x2c, 0x96, 0x2c, 0x5d, 0x18, 0x63, 0xe0, 0x45, 0x4c,
	0x5b, 0x62, 0x40, 0x37, 0xee, 0xe6, 0x9e, 0xf9, 0xdd, 0x7b, 0xcf, 0xed, 0x41, 0x07, 0x52, 0xc5,
	0x39, 0x3c, 0xf3, 0x29, 0x68, 0xc9, 0x26, 0x39, 0x68, 0xc0, 0x87, 0x46, 0x48, 0x23, 0xa1, 0xd8,
	0x40, 0xa6, 0x3a, 0x62, 0x8e, 0x68, 0x35, 0x87, 0x30, 0x04, 0x4b, 0x70, 0xf3, 0xe5, 0xe0, 0x16,
	0x8d, 0x41, 0x8d, 0x41, 0x71, 0x11, 0x29, 0xc9, 0xa7, 0x1d, 0x21, 0x75, 0xd4, 0xe1, 0x31, 0x24,
	0x99, 0xfb, 0xdf, 0x7e, 0x2f, 0xa1, 0xca, 0x03, 0x68, 0x89, 0x8f, 0x50, 0xcd, 0xec, 0xb8, 0x19,
	0x10, 0x3f, 0xf0, 0xc3, 0xff, 0xfd, 0x75, 0x85, 0x03, 0xd4, 0x10, 0xc5, 0x4c, 0xe6, 0xd7, 0x45,
	0x92, 0xea, 0x19, 0x29, 0x05, 0x7e, 0x58, 0xef, 0x6f, 0x4a, 0xb8, 0x8d, 0x76, 0x94, 0x4c, 0xd3,
	0x6f, 0xa4, 0x6c, 0x91, 0x2d, 0x0d, 0x5f, 0xa1, 0xdd, 0x5c, 0x3e, 0x15, 0xd9, 0xe0, 0x1e, 0xba,
	0xa6, 0x95, 0x54, 0x82, 0x72, 0xd8, 0xb8, 0x38, 0x66, 0xce, 0x1e, 0x33, 0xf6, 0xd8, 0xda, 0x1e,
	0xeb, 0x41, 0x92, 0x75, 0x2b, 0xf3, 0x8f, 0x13, 0xaf, 0xbf, 0xdd, 0x85, 0x7b, 0x66, 0x95, 0x29,
	0xef, 0xec, 0x70, 0x52, 0xfd, 0xdb, 0x94, 0xad, 0x26, 0x1c, 0xa2, 0x3d, 0x6b, 0xff, 0xb6, 0xc8,
	0x12, 0x35, 0x1a, 0xcb, 0x4c, 0x93, 0x9a, 0x3d, 0xf9, 0xa7, 0x8c, 0xcf, 0xd0, 0xbe, 0xbb, 0x62,
	0x03, 0xfd, 0x67, 0xd1, 0x5f, 0x3a, 0x6e, 0xa2, 0xaa, 0x79, 0xb1, 0x9c, 0xd4, 0x2d, 0xe0, 0x8a,
	0x6e, 0x6f, 0xbe, 0xa4, 0xfe, 0x62, 0x49, 0xfd, 0xcf, 0x25, 0xf5, 0x5f, 0x57, 0xd4, 0x5b, 0xac,
	0xa8, 0xf7, 0xb6, 0xa2, 0xde, 0xe3, 0xe9, 0x30, 0xd1, 0xa3, 0x42, 0xb0, 0x18, 0xc6, 0xdc, 0xe4,
	0x77, 0x6e, 0x12, 0xe5, 0x36, 0x51, 0xfe, 0xc2, 0xd7, 0xa9, 0xeb, 0xd9, 0x44, 0x2a, 0x51, 0xb3,
	0x51, 0x5d, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x27, 0x4c, 0x9a, 0x0c, 0x02, 0x00, 0x00,
}

func (m *Vote) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Vote) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Vote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Voter) > 0 {
		i -= len(m.Voter)
		copy(dAtA[i:], m.Voter)
		i = encodeVarintVote(dAtA, i, uint64(len(m.Voter)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.SellerPunishment) > 0 {
		i -= len(m.SellerPunishment)
		copy(dAtA[i:], m.SellerPunishment)
		i = encodeVarintVote(dAtA, i, uint64(len(m.SellerPunishment)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.BuyerPunishment) > 0 {
		i -= len(m.BuyerPunishment)
		copy(dAtA[i:], m.BuyerPunishment)
		i = encodeVarintVote(dAtA, i, uint64(len(m.BuyerPunishment)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.SendToSeller) > 0 {
		for iNdEx := len(m.SendToSeller) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SendToSeller[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintVote(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.RefundToBuyer) > 0 {
		for iNdEx := len(m.RefundToBuyer) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RefundToBuyer[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintVote(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.SellerGuilty {
		i--
		if m.SellerGuilty {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.BuyerGuilty {
		i--
		if m.BuyerGuilty {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.VoteId) > 0 {
		i -= len(m.VoteId)
		copy(dAtA[i:], m.VoteId)
		i = encodeVarintVote(dAtA, i, uint64(len(m.VoteId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintVote(dAtA []byte, offset int, v uint64) int {
	offset -= sovVote(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Vote) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.VoteId)
	if l > 0 {
		n += 1 + l + sovVote(uint64(l))
	}
	if m.BuyerGuilty {
		n += 2
	}
	if m.SellerGuilty {
		n += 2
	}
	if len(m.RefundToBuyer) > 0 {
		for _, e := range m.RefundToBuyer {
			l = e.Size()
			n += 1 + l + sovVote(uint64(l))
		}
	}
	if len(m.SendToSeller) > 0 {
		for _, e := range m.SendToSeller {
			l = e.Size()
			n += 1 + l + sovVote(uint64(l))
		}
	}
	l = len(m.BuyerPunishment)
	if l > 0 {
		n += 1 + l + sovVote(uint64(l))
	}
	l = len(m.SellerPunishment)
	if l > 0 {
		n += 1 + l + sovVote(uint64(l))
	}
	l = len(m.Voter)
	if l > 0 {
		n += 1 + l + sovVote(uint64(l))
	}
	return n
}

func sovVote(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVote(x uint64) (n int) {
	return sovVote(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Vote) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVote
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Vote: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Vote: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVote
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVote
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VoteId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuyerGuilty", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.BuyerGuilty = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SellerGuilty", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SellerGuilty = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RefundToBuyer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVote
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVote
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RefundToBuyer = append(m.RefundToBuyer, types.Coin{})
			if err := m.RefundToBuyer[len(m.RefundToBuyer)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SendToSeller", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVote
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVote
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SendToSeller = append(m.SendToSeller, types.Coin{})
			if err := m.SendToSeller[len(m.SendToSeller)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuyerPunishment", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVote
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVote
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BuyerPunishment = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SellerPunishment", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVote
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVote
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SellerPunishment = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Voter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVote
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVote
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Voter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVote(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVote
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVote(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVote
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVote
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVote
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVote
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVote
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVote
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVote        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVote          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVote = fmt.Errorf("proto: unexpected end of group")
)
